export const students = [
  {
    id: 1,
    first_name: "Morgun",
    last_name: "Purton",
    email: "mpurton0@cmu.edu",
    gender: "Male",
  },
  {
    id: 2,
    first_name: "Dorie",
    last_name: "Killough",
    email: "dkillough1@joomla.org",
    gender: "Male",
  },
  {
    id: 3,
    first_name: "Truda",
    last_name: "Cakes",
    email: "tcakes2@blog.com",
    gender: "Female",
  },
  {
    id: 4,
    first_name: "Andrey",
    last_name: "Caldicott",
    email: "acaldicott3@marketwatch.com",
    gender: "Male",
  },
  {
    id: 5,
    first_name: "Rhianna",
    last_name: "Vondra",
    email: "rvondra4@cnbc.com",
    gender: "Female",
  },
  {
    id: 6,
    first_name: "Halsy",
    last_name: "Ethelstone",
    email: "hethelstone5@baidu.com",
    gender: "Male",
  },
  {
    id: 7,
    first_name: "Robers",
    last_name: "Chinery",
    email: "rchinery6@yale.edu",
    gender: "Male",
  },
  {
    id: 8,
    first_name: "Davina",
    last_name: "Sperling",
    email: "dsperling7@youku.com",
    gender: "Female",
  },
  {
    id: 9,
    first_name: "Will",
    last_name: "Bitterton",
    email: "wbitterton8@omniture.com",
    gender: "Male",
  },
  {
    id: 10,
    first_name: "Adrianne",
    last_name: "Seares",
    email: "aseares9@alexa.com",
    gender: "Female",
  },
  {
    id: 11,
    first_name: "Esdras",
    last_name: "Quarrell",
    email: "equarrella@utexas.edu",
    gender: "Male",
  },
  {
    id: 12,
    first_name: "Iosep",
    last_name: "Clingoe",
    email: "iclingoeb@paypal.com",
    gender: "Male",
  },
  {
    id: 13,
    first_name: "Beatrisa",
    last_name: "Bamlett",
    email: "bbamlettc@ocn.ne.jp",
    gender: "Female",
  },
  {
    id: 14,
    first_name: "Roshelle",
    last_name: "Giovannilli",
    email: "rgiovannillid@skyrock.com",
    gender: "Female",
  },
  {
    id: 15,
    first_name: "Olympia",
    last_name: "Delucia",
    email: "odeluciae@spiegel.de",
    gender: "Female",
  },
  {
    id: 16,
    first_name: "Lilia",
    last_name: "Heffy",
    email: "lheffyf@bloglines.com",
    gender: "Female",
  },
  {
    id: 17,
    first_name: "Hanna",
    last_name: "Corneliussen",
    email: "hcorneliusseng@imageshack.us",
    gender: "Female",
  },
  {
    id: 18,
    first_name: "Parker",
    last_name: "Falkus",
    email: "pfalkush@infoseek.co.jp",
    gender: "Male",
  },
  {
    id: 19,
    first_name: "Toiboid",
    last_name: "Mushrow",
    email: "tmushrowi@is.gd",
    gender: "Male",
  },
  {
    id: 20,
    first_name: "Briant",
    last_name: "Maynard",
    email: "bmaynardj@t-online.de",
    gender: "Male",
  },
  {
    id: 21,
    first_name: "Valma",
    last_name: "Plaskett",
    email: "vplaskettk@mlb.com",
    gender: "Female",
  },
  {
    id: 22,
    first_name: "Rianon",
    last_name: "Persian",
    email: "rpersianl@nba.com",
    gender: "Female",
  },
  {
    id: 23,
    first_name: "Keene",
    last_name: "Barrat",
    email: "kbarratm@hatena.ne.jp",
    gender: "Male",
  },
  {
    id: 24,
    first_name: "Virgie",
    last_name: "Francecione",
    email: "vfrancecionen@wiley.com",
    gender: "Male",
  },
  {
    id: 25,
    first_name: "Berty",
    last_name: "Helin",
    email: "bhelino@techcrunch.com",
    gender: "Male",
  },
  {
    id: 26,
    first_name: "Stanislas",
    last_name: "Braddick",
    email: "sbraddickp@newyorker.com",
    gender: "Male",
  },
  {
    id: 27,
    first_name: "Conny",
    last_name: "Betz",
    email: "cbetzq@buzzfeed.com",
    gender: "Male",
  },
  {
    id: 28,
    first_name: "Carolann",
    last_name: "Howship",
    email: "chowshipr@foxnews.com",
    gender: "Female",
  },
  {
    id: 29,
    first_name: "Tomaso",
    last_name: "Artz",
    email: "tartzs@ftc.gov",
    gender: "Male",
  },
  {
    id: 30,
    first_name: "Stavro",
    last_name: "Dorning",
    email: "sdorningt@hibu.com",
    gender: "Male",
  },
  {
    id: 31,
    first_name: "Adria",
    last_name: "Carff",
    email: "acarffu@nytimes.com",
    gender: "Female",
  },
  {
    id: 32,
    first_name: "Hugues",
    last_name: "Aliman",
    email: "halimanv@naver.com",
    gender: "Male",
  },
  {
    id: 33,
    first_name: "Thorstein",
    last_name: "Schlagman",
    email: "tschlagmanw@marriott.com",
    gender: "Male",
  },
  {
    id: 34,
    first_name: "Hester",
    last_name: "Bryde",
    email: "hbrydex@sohu.com",
    gender: "Female",
  },
  {
    id: 35,
    first_name: "Shantee",
    last_name: "Sigert",
    email: "ssigerty@ftc.gov",
    gender: "Female",
  },
  {
    id: 36,
    first_name: "Reagen",
    last_name: "Bergen",
    email: "rbergenz@networksolutions.com",
    gender: "Male",
  },
  {
    id: 37,
    first_name: "Fabiano",
    last_name: "Marton",
    email: "fmarton10@w3.org",
    gender: "Male",
  },
  {
    id: 38,
    first_name: "Hermia",
    last_name: "Hehnke",
    email: "hhehnke11@e-recht24.de",
    gender: "Female",
  },
  {
    id: 39,
    first_name: "Emiline",
    last_name: "Deverille",
    email: "edeverille12@intel.com",
    gender: "Female",
  },
  {
    id: 40,
    first_name: "Neale",
    last_name: "Orrocks",
    email: "norrocks13@netvibes.com",
    gender: "Male",
  },
  {
    id: 41,
    first_name: "Ardine",
    last_name: "Cowderay",
    email: "acowderay14@wp.com",
    gender: "Female",
  },
  {
    id: 42,
    first_name: "Duff",
    last_name: "Brookzie",
    email: "dbrookzie15@goodreads.com",
    gender: "Male",
  },
  {
    id: 43,
    first_name: "Erin",
    last_name: "Hamsher",
    email: "ehamsher16@spotify.com",
    gender: "Female",
  },
  {
    id: 44,
    first_name: "Charlie",
    last_name: "Mincher",
    email: "cmincher17@free.fr",
    gender: "Male",
  },
  {
    id: 45,
    first_name: "Salmon",
    last_name: "Botly",
    email: "sbotly18@quantcast.com",
    gender: "Male",
  },
  {
    id: 46,
    first_name: "Rolando",
    last_name: "Ambrodi",
    email: "rambrodi19@ucoz.ru",
    gender: "Male",
  },
  {
    id: 47,
    first_name: "Siouxie",
    last_name: "Sear",
    email: "ssear1a@amazon.co.jp",
    gender: "Female",
  },
  {
    id: 48,
    first_name: "Clim",
    last_name: "Doxsey",
    email: "cdoxsey1b@wikipedia.org",
    gender: "Male",
  },
  {
    id: 49,
    first_name: "Jamill",
    last_name: "Edwicker",
    email: "jedwicker1c@sbwire.com",
    gender: "Male",
  },
  {
    id: 50,
    first_name: "Wilek",
    last_name: "Cartledge",
    email: "wcartledge1d@who.int",
    gender: "Male",
  },
];

export const femaleStudents = students.filter(
  (student) => student.gender === "Female"
);
